// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAw4qEgW9n1YmaW9llhA-VJbyF4gaKV7I',
    appId: '1:700939262875:web:2e540697d0d7a796771f3e',
    messagingSenderId: '700939262875',
    projectId: 'rescue-ace',
    authDomain: 'rescue-ace.firebaseapp.com',
    databaseURL: 'https://rescue-ace-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rescue-ace.firebasestorage.app',
    measurementId: 'G-C55C73DB2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN3I2d_lKg7nvm0QnuTk8wYjPKdKdhLa0',
    appId: '1:700939262875:android:97eaaed55528e410771f3e',
    messagingSenderId: '700939262875',
    projectId: 'rescue-ace',
    databaseURL: 'https://rescue-ace-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rescue-ace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcP1ST1Ra-njcDEtH6O4oS8v01CPI3yzU',
    appId: '1:700939262875:ios:0dc5d2d78639264e771f3e',
    messagingSenderId: '700939262875',
    projectId: 'rescue-ace',
    databaseURL: 'https://rescue-ace-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rescue-ace.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcP1ST1Ra-njcDEtH6O4oS8v01CPI3yzU',
    appId: '1:700939262875:ios:0dc5d2d78639264e771f3e',
    messagingSenderId: '700939262875',
    projectId: 'rescue-ace',
    databaseURL: 'https://rescue-ace-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rescue-ace.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAw4qEgW9n1YmaW9llhA-VJbyF4gaKV7I',
    appId: '1:700939262875:web:9708003236465abf771f3e',
    messagingSenderId: '700939262875',
    projectId: 'rescue-ace',
    authDomain: 'rescue-ace.firebaseapp.com',
    databaseURL: 'https://rescue-ace-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rescue-ace.firebasestorage.app',
    measurementId: 'G-G7HD7WB8CT',
  );
}
